package org.dync.teameeting.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table CHAT_ENITY.
 */
public class ChatEnity implements Serializable
{

    private Long id;
    private String meetingId;
    /**
     * send name ;
     */
    private String name;
    private String content;
    private String sendtime;

    public ChatEnity()
    {
    }

    public ChatEnity(Long id)
    {
        this.id = id;
    }

    public ChatEnity(Long id, String meetingId, String name, String content, String sendtime)
    {
        this.id = id;
        this.meetingId = meetingId;
        this.name = name;
        this.content = content;
        this.sendtime = sendtime;
    }

    public Long getId()
    {
        return id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    public String getMeetingId()
    {
        return meetingId;
    }

    public void setMeetingId(String meetingId)
    {
        this.meetingId = meetingId;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getContent()
    {
        return content;
    }

    public void setContent(String content)
    {
        this.content = content;
    }

    public String getSendtime()
    {
        return sendtime;
    }

    public void setSendtime(String sendtime)
    {
        this.sendtime = sendtime;
    }

    @Override
    public String toString()
    {
        return "ChatEnity{" +
                "meetingId='" + meetingId + '\'' +
                ", name='" + name + '\'' +
                ", content='" + content + '\'' +
                ", sendtime='" + sendtime + '\'' +
                '}';
    }
}
