package org.dync.teameeting.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatEnityDaoConfig;

    private final ChatEnityDao chatEnityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatEnityDaoConfig = daoConfigMap.get(ChatEnityDao.class).clone();
        chatEnityDaoConfig.initIdentityScope(type);

        chatEnityDao = new ChatEnityDao(chatEnityDaoConfig, this);

        registerDao(ChatEnity.class, chatEnityDao);
    }
    
    public void clear() {
        chatEnityDaoConfig.getIdentityScope().clear();
    }

    public ChatEnityDao getChatEnityDao() {
        return chatEnityDao;
    }

}
