package org.dync.teameeting.db.chatdao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table CHAT_CACHE_ENTITY.
 */
public class ChatCacheEntity implements Serializable {

    private Long id;
    private String meetingid;
    private String userid;
    private String content;
    private String sendtime;
    private Boolean isread;


    public static String MEETINGID = "MEETINGID";
    public static String USERID = "USERID";
    public static String CONTENT = "CONTENT";
    public static String SENDTIME = "SENDTIME";
    public static String ISREAD = "ISREAD";

    public ChatCacheEntity() {
    }

    public ChatCacheEntity(Long id) {
        this.id = id;
    }

    public ChatCacheEntity(Long id, String meetingid, String userid, String content, String sendtime, Boolean isread) {
        this.id = id;
        this.meetingid = meetingid;
        this.userid = userid;
        this.content = content;
        this.sendtime = sendtime;
        this.isread = isread;
    }

    public ChatCacheEntity(String meetingid, String userid, String content, String sendtime, Boolean isread) {
        this.meetingid = meetingid;
        this.userid = userid;
        this.content = content;
        this.sendtime = sendtime;
        this.isread = isread;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMeetingid() {
        return meetingid;
    }

    public void setMeetingid(String meetingid) {
        this.meetingid = meetingid;
    }

    public String getUserid() {
        return userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getSendtime() {
        return sendtime;
    }

    public long getSendtimeOrlong() {
        return Long.parseLong(sendtime);
    }

    public void setSendtime(String sendtime) {
        this.sendtime = sendtime;
    }

    public Boolean getIsread() {
        return isread;
    }

    public void setIsread(Boolean isread) {
        this.isread = isread;
    }

    @Override
    public String toString() {
        return "ChatCacheEntity{" +
                "meetingid='" + meetingid + '\'' +
                ", userid='" + userid + '\'' +
                ", content='" + content + '\'' +
                ", sendtime='" + sendtime + '\'' +
                ", isread=" + isread +
                '}';
    }


}
